/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

/**
 *
 * @author pc
 */
public class Ins_DatoSocialesEco extends javax.swing.JFrame {

    /**
     * Creates new form InscripcionDatoSocioEcon
     */
    public Ins_DatoSocialesEco() {
        initComponents();
        setBounds(125, 0, 1350, 845);
        setLocationRelativeTo(null);        
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Jta_PersonaSustenta = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        Jbtn_CancelarDatoSoeco = new javax.swing.JButton();
        Jbtn_guardarDatoSoeco = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        Jtf_Fijo = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        Jtf_Esporadico = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        Jtf_Propio = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        Jtf_OtrosIngresos = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        Jtf_TotalIngresos = new javax.swing.JTextField();
        Jtf_Gastos = new javax.swing.JTextField();
        jLabImagen = new javax.swing.JLabel();
        jPanelColor = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(228, 244, 251));
        jPanel2.setToolTipText("");

        jLabel.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jLabel.setText("Datos Socioeconómicos");

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel3.setText("Personas que sustentan el hogar:");

        Jta_PersonaSustenta.setColumns(20);
        Jta_PersonaSustenta.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        Jta_PersonaSustenta.setRows(5);
        jScrollPane1.setViewportView(Jta_PersonaSustenta);

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel1.setText("Formas de trabajo: ");

        jLabel9.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel9.setText("Gastos mensuales:");

        Jbtn_CancelarDatoSoeco.setBackground(new java.awt.Color(71, 82, 94));
        Jbtn_CancelarDatoSoeco.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Jbtn_CancelarDatoSoeco.setForeground(new java.awt.Color(255, 255, 255));
        Jbtn_CancelarDatoSoeco.setText("Cancelar");
        Jbtn_CancelarDatoSoeco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jbtn_CancelarDatoSoecoActionPerformed(evt);
            }
        });

        Jbtn_guardarDatoSoeco.setBackground(new java.awt.Color(71, 82, 94));
        Jbtn_guardarDatoSoeco.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Jbtn_guardarDatoSoeco.setForeground(new java.awt.Color(255, 255, 255));
        Jbtn_guardarDatoSoeco.setText("Guardar");
        Jbtn_guardarDatoSoeco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jbtn_guardarDatoSoecoActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel4.setText("Fijo:");

        Jtf_Fijo.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        Jtf_Fijo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jtf_FijoActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel5.setText("Esporádicos:");

        Jtf_Esporadico.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        Jtf_Esporadico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jtf_EsporadicoActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel6.setText("Propio:");

        Jtf_Propio.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        Jtf_Propio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jtf_PropioActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel7.setText("Otros ingresos:");

        Jtf_OtrosIngresos.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        Jtf_OtrosIngresos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jtf_OtrosIngresosActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel8.setText("Total de ingresos:");

        Jtf_TotalIngresos.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Jtf_TotalIngresos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jtf_TotalIngresosActionPerformed(evt);
            }
        });

        Jtf_Gastos.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        Jtf_Gastos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jtf_GastosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 484, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 461, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 484, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel7)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(Jtf_OtrosIngresos, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(62, 62, 62)
                            .addComponent(jLabel8)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(Jtf_TotalIngresos))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 945, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel4)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(Jtf_Fijo, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(100, 100, 100)
                            .addComponent(jLabel5)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(Jtf_Esporadico, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(Jtf_Propio, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(Jtf_Gastos, javax.swing.GroupLayout.DEFAULT_SIZE, 948, Short.MAX_VALUE))
                .addContainerGap(102, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(347, 347, 347)
                        .addComponent(Jbtn_guardarDatoSoeco)
                        .addGap(180, 180, 180)
                        .addComponent(Jbtn_CancelarDatoSoeco))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(402, 402, 402)
                        .addComponent(jLabel)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel)
                .addGap(26, 26, 26)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jLabel2))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(Jtf_Fijo, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(Jtf_Esporadico, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Jtf_Propio, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(Jtf_OtrosIngresos, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(Jtf_TotalIngresos, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addComponent(Jtf_Gastos, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Jbtn_guardarDatoSoeco)
                    .addComponent(Jbtn_CancelarDatoSoeco))
                .addContainerGap(90, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, 1150, 680));

        jLabImagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/buen-pastor.jpg"))); // NOI18N
        getContentPane().add(jLabImagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1350, 800));

        jPanelColor.setBackground(new java.awt.Color(109, 146, 199));

        javax.swing.GroupLayout jPanelColorLayout = new javax.swing.GroupLayout(jPanelColor);
        jPanelColor.setLayout(jPanelColorLayout);
        jPanelColorLayout.setHorizontalGroup(
            jPanelColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1350, Short.MAX_VALUE)
        );
        jPanelColorLayout.setVerticalGroup(
            jPanelColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        getContentPane().add(jPanelColor, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1350, 50));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Jtf_FijoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jtf_FijoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Jtf_FijoActionPerformed

    private void Jtf_EsporadicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jtf_EsporadicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Jtf_EsporadicoActionPerformed

    private void Jtf_PropioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jtf_PropioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Jtf_PropioActionPerformed

    private void Jtf_OtrosIngresosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jtf_OtrosIngresosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Jtf_OtrosIngresosActionPerformed

    private void Jtf_TotalIngresosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jtf_TotalIngresosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Jtf_TotalIngresosActionPerformed

    private void Jtf_GastosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jtf_GastosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Jtf_GastosActionPerformed

    private void Jbtn_CancelarDatoSoecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jbtn_CancelarDatoSoecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Jbtn_CancelarDatoSoecoActionPerformed

    private void Jbtn_guardarDatoSoecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jbtn_guardarDatoSoecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Jbtn_guardarDatoSoecoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ins_DatoSocialesEco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ins_DatoSocialesEco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ins_DatoSocialesEco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ins_DatoSocialesEco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ins_DatoSocialesEco().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Jbtn_CancelarDatoSoeco;
    private javax.swing.JButton Jbtn_guardarDatoSoeco;
    private javax.swing.JTextArea Jta_PersonaSustenta;
    private javax.swing.JTextField Jtf_Esporadico;
    private javax.swing.JTextField Jtf_Fijo;
    private javax.swing.JTextField Jtf_Gastos;
    private javax.swing.JTextField Jtf_OtrosIngresos;
    private javax.swing.JTextField Jtf_Propio;
    private javax.swing.JTextField Jtf_TotalIngresos;
    private javax.swing.JLabel jLabImagen;
    private javax.swing.JLabel jLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanelColor;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
