/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

/**
 *
 * @author pc
 */
public class Ins_DatoImportantes extends javax.swing.JFrame {

    /**
     * Creates new form InscripcionDatoSocioEcon
     */
    public Ins_DatoImportantes() {
        initComponents();
        setBounds(125, 0, 1350, 845);
        setLocationRelativeTo(null);        
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        Jtf_Television = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        Jtf_Computadora = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        Jtf_Acondicionado = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        Jtf_Otros = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        Jtf_TotalIngresos = new javax.swing.JTextField();
        jPanel12 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        Jtf_Marca = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        Jtf_Anio = new javax.swing.JTextField();
        jPanel15 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        Jrb_SiVehiculo = new javax.swing.JRadioButton();
        Jrb_NoVehiculo = new javax.swing.JRadioButton();
        jPanel11 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        Jrb_SiEmpleada = new javax.swing.JRadioButton();
        Jrb_NoEmpleada = new javax.swing.JRadioButton();
        jLabel11 = new javax.swing.JLabel();
        Jtf_IngresoEmpleada = new javax.swing.JTextField();
        Jbtn_guardarDatoImp = new javax.swing.JButton();
        Jbtn_cancelarDatoImp = new javax.swing.JButton();
        jLabImagen = new javax.swing.JLabel();
        jPanelColor = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(228, 244, 251));

        jLabel.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jLabel.setText("Datos Importantes ");

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel1.setText("Formas de trabajo: ");

        jPanel5.setBackground(new java.awt.Color(228, 244, 251));

        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel4.setText("Televisor:");

        Jtf_Television.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        Jtf_Television.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jtf_TelevisionActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel5.setText("Computadora:");

        Jtf_Computadora.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        Jtf_Computadora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jtf_ComputadoraActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel6.setText("A. Acondicionado:");

        Jtf_Acondicionado.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        Jtf_Acondicionado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jtf_AcondicionadoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(125, 125, 125)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Jtf_Television, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(Jtf_Computadora, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(Jtf_Acondicionado, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(Jtf_Computadora, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(Jtf_Acondicionado, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Jtf_Television, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );

        jPanel8.setBackground(new java.awt.Color(228, 244, 251));

        jLabel7.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel7.setText("Otros:");

        Jtf_Otros.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        Jtf_Otros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jtf_OtrosActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel8.setText("Total de ingresos:");

        Jtf_TotalIngresos.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        Jtf_TotalIngresos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jtf_TotalIngresosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(127, 127, 127)
                .addComponent(jLabel7)
                .addGap(53, 53, 53)
                .addComponent(Jtf_Otros, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59)
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addComponent(Jtf_TotalIngresos, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(952, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel8)
                        .addComponent(Jtf_TotalIngresos, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7)
                        .addComponent(Jtf_Otros, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel12.setBackground(new java.awt.Color(228, 244, 251));
        jPanel12.setForeground(new java.awt.Color(200, 199, 199));

        jLabel14.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel14.setText("Marca:");

        Jtf_Marca.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        Jtf_Marca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jtf_MarcaActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel12.setText("Año:");

        Jtf_Anio.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        Jtf_Anio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jtf_AnioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(134, 134, 134)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Jtf_Marca, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(Jtf_Anio, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Jtf_Marca, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(Jtf_Anio, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addContainerGap())
        );

        jPanel15.setBackground(new java.awt.Color(228, 244, 251));

        jLabel13.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel13.setText("Tiene vehiculo propio:");

        Jrb_SiVehiculo.setBackground(new java.awt.Color(228, 244, 251));
        Jrb_SiVehiculo.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        Jrb_SiVehiculo.setText("Si");
        Jrb_SiVehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jrb_SiVehiculoActionPerformed(evt);
            }
        });

        Jrb_NoVehiculo.setBackground(new java.awt.Color(228, 244, 251));
        Jrb_NoVehiculo.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        Jrb_NoVehiculo.setText("No");

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Jrb_SiVehiculo)
                .addGap(26, 26, 26)
                .addComponent(Jrb_NoVehiculo)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel15Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(Jrb_SiVehiculo)
                    .addComponent(Jrb_NoVehiculo)))
        );

        jPanel11.setBackground(new java.awt.Color(228, 244, 251));

        jLabel10.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel10.setText("Tiene empleada domestica: ");

        Jrb_SiEmpleada.setBackground(new java.awt.Color(228, 244, 251));
        Jrb_SiEmpleada.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        Jrb_SiEmpleada.setText("Si");
        Jrb_SiEmpleada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jrb_SiEmpleadaActionPerformed(evt);
            }
        });

        Jrb_NoEmpleada.setBackground(new java.awt.Color(228, 244, 251));
        Jrb_NoEmpleada.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        Jrb_NoEmpleada.setText("No");

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Jrb_SiEmpleada)
                .addGap(18, 18, 18)
                .addComponent(Jrb_NoEmpleada)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addGap(0, 11, Short.MAX_VALUE)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(Jrb_SiEmpleada)
                    .addComponent(Jrb_NoEmpleada)))
        );

        jLabel11.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel11.setText("Cuales son sus ingresos:");

        Jtf_IngresoEmpleada.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        Jtf_IngresoEmpleada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jtf_IngresoEmpleadaActionPerformed(evt);
            }
        });

        Jbtn_guardarDatoImp.setBackground(new java.awt.Color(71, 82, 94));
        Jbtn_guardarDatoImp.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        Jbtn_guardarDatoImp.setForeground(new java.awt.Color(255, 255, 255));
        Jbtn_guardarDatoImp.setText("Guardar");
        Jbtn_guardarDatoImp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jbtn_guardarDatoImpActionPerformed(evt);
            }
        });

        Jbtn_cancelarDatoImp.setBackground(new java.awt.Color(71, 82, 94));
        Jbtn_cancelarDatoImp.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        Jbtn_cancelarDatoImp.setForeground(new java.awt.Color(255, 255, 255));
        Jbtn_cancelarDatoImp.setText("Cancelar");
        Jbtn_cancelarDatoImp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jbtn_cancelarDatoImpActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(103, 103, 103)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 484, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(138, 138, 138)
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Jtf_IngresoEmpleada, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(43, 43, 43)
                                        .addComponent(Jbtn_guardarDatoImp)
                                        .addGap(199, 199, 199)
                                        .addComponent(Jbtn_cancelarDatoImp)))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(470, 470, 470)
                .addComponent(jLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(Jtf_IngresoEmpleada, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(72, 72, 72)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Jbtn_cancelarDatoImp)
                    .addComponent(Jbtn_guardarDatoImp))
                .addContainerGap(96, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, 1150, 690));

        jLabImagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/buen-pastor.jpg"))); // NOI18N
        getContentPane().add(jLabImagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1350, 800));

        jPanelColor.setBackground(new java.awt.Color(109, 146, 199));

        javax.swing.GroupLayout jPanelColorLayout = new javax.swing.GroupLayout(jPanelColor);
        jPanelColor.setLayout(jPanelColorLayout);
        jPanelColorLayout.setHorizontalGroup(
            jPanelColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1350, Short.MAX_VALUE)
        );
        jPanelColorLayout.setVerticalGroup(
            jPanelColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        getContentPane().add(jPanelColor, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1350, 50));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Jtf_TelevisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jtf_TelevisionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Jtf_TelevisionActionPerformed

    private void Jtf_AcondicionadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jtf_AcondicionadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Jtf_AcondicionadoActionPerformed

    private void Jtf_OtrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jtf_OtrosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Jtf_OtrosActionPerformed

    private void Jtf_TotalIngresosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jtf_TotalIngresosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Jtf_TotalIngresosActionPerformed

    private void Jtf_IngresoEmpleadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jtf_IngresoEmpleadaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Jtf_IngresoEmpleadaActionPerformed

    private void Jrb_SiEmpleadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jrb_SiEmpleadaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Jrb_SiEmpleadaActionPerformed

    private void Jtf_MarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jtf_MarcaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Jtf_MarcaActionPerformed

    private void Jtf_AnioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jtf_AnioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Jtf_AnioActionPerformed

    private void Jrb_SiVehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jrb_SiVehiculoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Jrb_SiVehiculoActionPerformed

    private void Jtf_ComputadoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jtf_ComputadoraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Jtf_ComputadoraActionPerformed

    private void Jbtn_cancelarDatoImpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jbtn_cancelarDatoImpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Jbtn_cancelarDatoImpActionPerformed

    private void Jbtn_guardarDatoImpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jbtn_guardarDatoImpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Jbtn_guardarDatoImpActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ins_DatoImportantes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ins_DatoImportantes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ins_DatoImportantes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ins_DatoImportantes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ins_DatoImportantes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Jbtn_cancelarDatoImp;
    private javax.swing.JButton Jbtn_guardarDatoImp;
    private javax.swing.JRadioButton Jrb_NoEmpleada;
    private javax.swing.JRadioButton Jrb_NoVehiculo;
    private javax.swing.JRadioButton Jrb_SiEmpleada;
    private javax.swing.JRadioButton Jrb_SiVehiculo;
    private javax.swing.JTextField Jtf_Acondicionado;
    private javax.swing.JTextField Jtf_Anio;
    private javax.swing.JTextField Jtf_Computadora;
    private javax.swing.JTextField Jtf_IngresoEmpleada;
    private javax.swing.JTextField Jtf_Marca;
    private javax.swing.JTextField Jtf_Otros;
    private javax.swing.JTextField Jtf_Television;
    private javax.swing.JTextField Jtf_TotalIngresos;
    private javax.swing.JLabel jLabImagen;
    private javax.swing.JLabel jLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanelColor;
    // End of variables declaration//GEN-END:variables
}
