/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

/**
 *
 * @author steve
 */
public class Ins_Personal extends javax.swing.JFrame {

    /**
     * Creates new form Ins_Personal
     */
    public Ins_Personal() {
        initComponents();
        setBounds(125, 0, 1350, 845);
        setLocationRelativeTo(null);        
        this.setResizable(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Btg_problemaSalud = new javax.swing.ButtonGroup();
        Btg_Escolaridad = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        Jtf_Apellidos = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        Jtf_Nombres = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        Jtf_Telefono = new javax.swing.JTextField();
        Jcb_Religion = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        Jtf_Correo = new javax.swing.JTextField();
        Jbtn_inscCurso = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        Jtf_trabajoPadre = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        Jtf_cargoPadre = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        Jtf_telefonoPadre = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        Jta_problemasSalud = new javax.swing.JTextArea();
        jLabel16 = new javax.swing.JLabel();
        Jcb_estadoCivilPadre = new javax.swing.JComboBox<>();
        jLabel17 = new javax.swing.JLabel();
        Jtf_trabajoMadre = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        Jtf_gradoInstitucion = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        Jtf_telefonoMadre = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        Jcb_estadoCivilMadre = new javax.swing.JComboBox<>();
        Jbtn_datoSocioEconomico = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jLabel23 = new javax.swing.JLabel();
        Jtf_Institucion = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        Jtf_cargoMadre = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        Jtf_docenteInstitucion = new javax.swing.JTextField();
        Jtf_ubicacionInstitucion = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        Jtf_numDocente = new javax.swing.JTextField();
        Jbtn_datoImportante = new javax.swing.JButton();
        Jbtn_cancelar = new javax.swing.JButton();
        Jbtn_guardar = new javax.swing.JButton();
        jLabel28 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setPreferredSize(new java.awt.Dimension(1350, 2000));

        jScrollPane6.setAutoscrolls(true);
        jScrollPane6.setPreferredSize(new java.awt.Dimension(1350, 2000));

        jPanel3.setBackground(new java.awt.Color(228, 244, 251));
        jPanel3.setPreferredSize(new java.awt.Dimension(1350, 2800));

        jLabel5.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jLabel5.setText("Trabajo de los padres");

        Jtf_Apellidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jtf_ApellidosActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel6.setText("Apellidos:");

        jLabel7.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel7.setText("Nombre:");

        Jtf_Nombres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jtf_NombresActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel8.setText("Teléfono:");

        jLabel9.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel9.setText("Religión:");

        Jtf_Telefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jtf_TelefonoActionPerformed(evt);
            }
        });

        Jcb_Religion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cristiano", "Católico", "Ateo", "Testigo de Jehová" }));

        jLabel10.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel10.setText("Correo:");

        Jtf_Correo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jtf_CorreoActionPerformed(evt);
            }
        });

        Jbtn_inscCurso.setBackground(new java.awt.Color(71, 82, 94));
        Jbtn_inscCurso.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        Jbtn_inscCurso.setForeground(new java.awt.Color(255, 255, 255));
        Jbtn_inscCurso.setText("Inscripción de actividad");
        Jbtn_inscCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jbtn_inscCursoActionPerformed(evt);
            }
        });
        Jbtn_inscCurso.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Jbtn_inscCursoKeyPressed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel11.setText("Problemas de salud:");

        Btg_problemaSalud.add(jRadioButton1);
        jRadioButton1.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jRadioButton1.setText("Si");

        Btg_problemaSalud.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jRadioButton2.setText("No");

        jLabel12.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jLabel12.setText("Inscripción de Persona ");

        jLabel13.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel13.setText("Lugar de trabajo del padre");

        Jtf_trabajoPadre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jtf_trabajoPadreActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel14.setText("Telefono:");

        Jtf_cargoPadre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jtf_cargoPadreActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel15.setText("Cargo:");

        Jtf_telefonoPadre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jtf_telefonoPadreActionPerformed(evt);
            }
        });

        Jta_problemasSalud.setColumns(20);
        Jta_problemasSalud.setRows(5);
        jScrollPane1.setViewportView(Jta_problemasSalud);

        jLabel16.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel16.setText("Estado civil:");

        Jcb_estadoCivilPadre.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Casado", "Soltero", "Divorciado", "Union de hecho", "Viudo" }));

        jLabel17.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel17.setText("Lugar de trabajo de la madre");

        Jtf_trabajoMadre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jtf_trabajoMadreActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel18.setText("Cargo:");

        Jtf_gradoInstitucion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jtf_gradoInstitucionActionPerformed(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel19.setText("Telefono:");

        Jtf_telefonoMadre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jtf_telefonoMadreActionPerformed(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel20.setText("Estado civil:");

        Jcb_estadoCivilMadre.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Casado", "Soltero", "Divorciado", "Union de hecho", "Viudo" }));

        Jbtn_datoSocioEconomico.setBackground(new java.awt.Color(71, 82, 94));
        Jbtn_datoSocioEconomico.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        Jbtn_datoSocioEconomico.setForeground(new java.awt.Color(255, 255, 255));
        Jbtn_datoSocioEconomico.setText("Datos socio económicos");

        jLabel21.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jLabel21.setText("Datos escolares");

        jLabel22.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel22.setText("Escolaridad:");

        Btg_Escolaridad.add(jRadioButton3);
        jRadioButton3.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jRadioButton3.setText("Primaria");

        Btg_Escolaridad.add(jRadioButton4);
        jRadioButton4.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jRadioButton4.setText("Secundaria");

        jLabel23.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel23.setText("Nombre de la institución");

        Jtf_Institucion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jtf_InstitucionActionPerformed(evt);
            }
        });

        jLabel24.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel24.setText("Grado:");

        Jtf_cargoMadre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jtf_cargoMadreActionPerformed(evt);
            }
        });

        jLabel25.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel25.setText("Número del docente:");

        Jtf_docenteInstitucion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jtf_docenteInstitucionActionPerformed(evt);
            }
        });

        Jtf_ubicacionInstitucion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jtf_ubicacionInstitucionActionPerformed(evt);
            }
        });

        jLabel27.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel27.setText("Ubicación de la institución");

        Jtf_numDocente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jtf_numDocenteActionPerformed(evt);
            }
        });

        Jbtn_datoImportante.setBackground(new java.awt.Color(71, 82, 94));
        Jbtn_datoImportante.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        Jbtn_datoImportante.setForeground(new java.awt.Color(255, 255, 255));
        Jbtn_datoImportante.setText("Datos importantes");

        Jbtn_cancelar.setBackground(new java.awt.Color(71, 82, 94));
        Jbtn_cancelar.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        Jbtn_cancelar.setForeground(new java.awt.Color(255, 255, 255));
        Jbtn_cancelar.setText("Cancelar");
        Jbtn_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jbtn_cancelarActionPerformed(evt);
            }
        });

        Jbtn_guardar.setBackground(new java.awt.Color(71, 82, 94));
        Jbtn_guardar.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        Jbtn_guardar.setForeground(new java.awt.Color(255, 255, 255));
        Jbtn_guardar.setText("Guardar");
        Jbtn_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jbtn_guardarActionPerformed(evt);
            }
        });

        jLabel28.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel28.setText("Nombre del docente:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(531, 531, 531)
                        .addComponent(jLabel12))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(144, 144, 144)
                        .addComponent(jLabel7)
                        .addGap(21, 21, 21)
                        .addComponent(Jtf_Nombres, javax.swing.GroupLayout.PREFERRED_SIZE, 937, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(138, 138, 138)
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(Jtf_Apellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 937, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(138, 138, 138)
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(Jtf_Telefono, javax.swing.GroupLayout.PREFERRED_SIZE, 506, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(jLabel9)
                        .addGap(47, 47, 47)
                        .addComponent(Jcb_Religion, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(138, 138, 138)
                        .addComponent(jLabel10)
                        .addGap(35, 35, 35)
                        .addComponent(Jtf_Correo, javax.swing.GroupLayout.PREFERRED_SIZE, 619, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(59, 59, 59)
                        .addComponent(Jbtn_inscCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(138, 138, 138)
                        .addComponent(jLabel11)
                        .addGap(32, 32, 32)
                        .addComponent(jRadioButton1)
                        .addGap(18, 18, 18)
                        .addComponent(jRadioButton2))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(138, 138, 138)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1036, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(138, 138, 138)
                        .addComponent(Jtf_trabajoPadre, javax.swing.GroupLayout.PREFERRED_SIZE, 788, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(jLabel15)
                        .addGap(15, 15, 15)
                        .addComponent(Jtf_cargoPadre, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(56, 56, 56)
                        .addComponent(jLabel14)
                        .addGap(29, 29, 29)
                        .addComponent(Jtf_telefonoPadre, javax.swing.GroupLayout.PREFERRED_SIZE, 424, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(jLabel16)
                        .addGap(18, 18, 18)
                        .addComponent(Jcb_estadoCivilPadre, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(jLabel17))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(Jtf_trabajoMadre, javax.swing.GroupLayout.PREFERRED_SIZE, 1036, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(540, 540, 540)
                        .addComponent(jLabel21))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(jLabel22)
                        .addGap(28, 28, 28)
                        .addComponent(jRadioButton3)
                        .addGap(27, 27, 27)
                        .addComponent(jRadioButton4))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(jLabel23))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(Jtf_Institucion, javax.swing.GroupLayout.PREFERRED_SIZE, 1036, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(jLabel24)
                        .addGap(3, 3, 3)
                        .addComponent(Jtf_gradoInstitucion, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(jLabel28)
                        .addGap(18, 18, 18)
                        .addComponent(Jtf_docenteInstitucion, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(jLabel25)
                        .addGap(5, 5, 5)
                        .addComponent(Jtf_numDocente, javax.swing.GroupLayout.PREFERRED_SIZE, 851, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(jLabel27))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(Jtf_ubicacionInstitucion, javax.swing.GroupLayout.PREFERRED_SIZE, 1036, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(500, 500, 500)
                        .addComponent(Jbtn_datoImportante, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(256, 256, 256)
                        .addComponent(Jbtn_guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(438, 438, 438)
                        .addComponent(Jbtn_cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel18)
                                .addGap(18, 18, 18)
                                .addComponent(Jtf_cargoMadre, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel19)
                                .addGap(27, 27, 27)
                                .addComponent(Jtf_telefonoMadre, javax.swing.GroupLayout.PREFERRED_SIZE, 424, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel20)
                                .addGap(18, 18, 18)
                                .addComponent(Jcb_estadoCivilMadre, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(341, 341, 341)
                                .addComponent(Jbtn_datoSocioEconomico, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(509, 509, 509)
                        .addComponent(jLabel5))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(138, 138, 138)
                        .addComponent(jLabel13)))
                .addContainerGap(176, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel12)
                .addGap(30, 30, 30)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabel7))
                    .addComponent(Jtf_Nombres, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabel6))
                    .addComponent(Jtf_Apellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Jtf_Telefono, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Jcb_Religion, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9))))
                .addGap(25, 25, 25)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jLabel10))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(Jtf_Correo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Jbtn_inscCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButton1)
                            .addComponent(jRadioButton2))))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(jLabel5)
                .addGap(24, 24, 24)
                .addComponent(jLabel13)
                .addGap(18, 18, 18)
                .addComponent(Jtf_trabajoPadre, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel15))
                    .addComponent(Jtf_cargoPadre, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel14))
                    .addComponent(Jtf_telefonoPadre, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(Jcb_estadoCivilPadre, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(jLabel17)
                .addGap(19, 19, 19)
                .addComponent(Jtf_trabajoMadre, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(Jtf_cargoMadre, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19)
                    .addComponent(Jtf_telefonoMadre, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(Jcb_estadoCivilMadre, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel20)
                            .addComponent(Jbtn_datoSocioEconomico, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(45, 45, 45)
                .addComponent(jLabel21)
                .addGap(22, 22, 22)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jRadioButton3)
                        .addComponent(jLabel22))
                    .addComponent(jRadioButton4))
                .addGap(27, 27, 27)
                .addComponent(jLabel23)
                .addGap(19, 19, 19)
                .addComponent(Jtf_Institucion, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel24))
                    .addComponent(Jtf_gradoInstitucion, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Jtf_docenteInstitucion, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel28)))
                .addGap(25, 25, 25)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel25))
                    .addComponent(Jtf_numDocente, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addComponent(jLabel27)
                .addGap(9, 9, 9)
                .addComponent(Jtf_ubicacionInstitucion, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(Jbtn_datoImportante, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Jbtn_cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Jbtn_guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1167, 1167, 1167))
        );

        jScrollPane6.setViewportView(jPanel3);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 1317, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(557, 557, 557))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Jtf_ApellidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jtf_ApellidosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Jtf_ApellidosActionPerformed

    private void Jtf_NombresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jtf_NombresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Jtf_NombresActionPerformed

    private void Jtf_TelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jtf_TelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Jtf_TelefonoActionPerformed

    private void Jtf_CorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jtf_CorreoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Jtf_CorreoActionPerformed

    private void Jtf_trabajoPadreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jtf_trabajoPadreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Jtf_trabajoPadreActionPerformed

    private void Jtf_cargoPadreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jtf_cargoPadreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Jtf_cargoPadreActionPerformed

    private void Jtf_telefonoPadreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jtf_telefonoPadreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Jtf_telefonoPadreActionPerformed

    private void Jtf_trabajoMadreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jtf_trabajoMadreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Jtf_trabajoMadreActionPerformed

    private void Jtf_gradoInstitucionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jtf_gradoInstitucionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Jtf_gradoInstitucionActionPerformed

    private void Jtf_telefonoMadreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jtf_telefonoMadreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Jtf_telefonoMadreActionPerformed

    private void Jtf_InstitucionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jtf_InstitucionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Jtf_InstitucionActionPerformed

    private void Jtf_cargoMadreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jtf_cargoMadreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Jtf_cargoMadreActionPerformed

    private void Jtf_docenteInstitucionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jtf_docenteInstitucionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Jtf_docenteInstitucionActionPerformed

    private void Jtf_ubicacionInstitucionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jtf_ubicacionInstitucionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Jtf_ubicacionInstitucionActionPerformed

    private void Jtf_numDocenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jtf_numDocenteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Jtf_numDocenteActionPerformed

    private void Jbtn_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jbtn_cancelarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Jbtn_cancelarActionPerformed

    private void Jbtn_inscCursoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Jbtn_inscCursoKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_Jbtn_inscCursoKeyPressed

    private void Jbtn_inscCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jbtn_inscCursoActionPerformed
        inscribirNavegacion();
    }//GEN-LAST:event_Jbtn_inscCursoActionPerformed

    private void Jbtn_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jbtn_guardarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Jbtn_guardarActionPerformed

    public void inscribirNavegacion(){
        Ins_Curso_per btncurso = new Ins_Curso_per();
        btncurso.setVisible(true);
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ins_Personal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ins_Personal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ins_Personal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ins_Personal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ins_Personal().setVisible(true);
                
            }
        });
    } 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup Btg_Escolaridad;
    private javax.swing.ButtonGroup Btg_problemaSalud;
    private javax.swing.JButton Jbtn_cancelar;
    private javax.swing.JButton Jbtn_datoImportante;
    private javax.swing.JButton Jbtn_datoSocioEconomico;
    private javax.swing.JButton Jbtn_guardar;
    private javax.swing.JButton Jbtn_inscCurso;
    private javax.swing.JComboBox<String> Jcb_Religion;
    private javax.swing.JComboBox<String> Jcb_estadoCivilMadre;
    private javax.swing.JComboBox<String> Jcb_estadoCivilPadre;
    private javax.swing.JTextArea Jta_problemasSalud;
    private javax.swing.JTextField Jtf_Apellidos;
    private javax.swing.JTextField Jtf_Correo;
    private javax.swing.JTextField Jtf_Institucion;
    private javax.swing.JTextField Jtf_Nombres;
    private javax.swing.JTextField Jtf_Telefono;
    private javax.swing.JTextField Jtf_cargoMadre;
    private javax.swing.JTextField Jtf_cargoPadre;
    private javax.swing.JTextField Jtf_docenteInstitucion;
    private javax.swing.JTextField Jtf_gradoInstitucion;
    private javax.swing.JTextField Jtf_numDocente;
    private javax.swing.JTextField Jtf_telefonoMadre;
    private javax.swing.JTextField Jtf_telefonoPadre;
    private javax.swing.JTextField Jtf_trabajoMadre;
    private javax.swing.JTextField Jtf_trabajoPadre;
    private javax.swing.JTextField Jtf_ubicacionInstitucion;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane6;
    // End of variables declaration//GEN-END:variables
}
