/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

/**
 *
 * @author CGCF
 */
public class Menu_Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Menu_Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton_Registro = new javax.swing.JButton();
        jButton_ConsultaAsis = new javax.swing.JButton();
        jButton_Beneficiarios = new javax.swing.JButton();
        jButton_Registro1 = new javax.swing.JButton();
        jLabel_Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton_Registro.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jButton_Registro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/DataUsers.png"))); // NOI18N
        jButton_Registro.setText("Datos Usuario");
        jButton_Registro.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton_Registro.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jPanel1.add(jButton_Registro, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 400, 290));

        jButton_ConsultaAsis.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jButton_ConsultaAsis.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ListGr.png"))); // NOI18N
        jButton_ConsultaAsis.setText("Consultar Asistencia");
        jButton_ConsultaAsis.setToolTipText("");
        jButton_ConsultaAsis.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton_ConsultaAsis.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jPanel1.add(jButton_ConsultaAsis, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, 400, 290));

        jButton_Beneficiarios.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jButton_Beneficiarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Beneficiarios.png"))); // NOI18N
        jButton_Beneficiarios.setText("Beneficiarios");
        jButton_Beneficiarios.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton_Beneficiarios.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jPanel1.add(jButton_Beneficiarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 370, 400, 290));

        jButton_Registro1.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jButton_Registro1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/RegistroAsis.png"))); // NOI18N
        jButton_Registro1.setText("Registro de Asistencia");
        jButton_Registro1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton_Registro1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jPanel1.add(jButton_Registro1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 60, 400, 290));

        jLabel_Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/buenpastor.jpg"))); // NOI18N
        jPanel1.add(jLabel_Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1130, 760));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu_Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jButton_Beneficiarios;
    public javax.swing.JButton jButton_ConsultaAsis;
    public javax.swing.JButton jButton_Registro;
    public javax.swing.JButton jButton_Registro1;
    private javax.swing.JLabel jLabel_Fondo;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
